FROM node:20-alpine AS base
# If you want to build docker in China
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

## Install dependencies only when needed
FROM base AS builder

ENV NPM_CONFIG_LOGLEVEL warn

# To increase the memory limit for the Node.js process
ENV NODE_OPTIONS=--max_old_space_size=4096

RUN corepack enable

RUN apk add --upgrade --no-cache vips-dev build-base
RUN apk add --upgrade --no-cache g++ make python3

WORKDIR /app

COPY package.json ./

# If you want to build docker in China
RUN npm config set registry https://registry.npmmirror.com/

RUN pnpm install

COPY . .

 # run build standalone for docker version
RUN pnpm build:docker

## Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production

# add proxychains for HTTP_PROXY_URL
RUN apk add --no-cache proxychains-ng

# Set the correct permission for prerender cache
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
#COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.pnpm ./node_modules/.pnpm

USER nextjs

EXPOSE 3210

# set hostname to localhost
ENV HOSTNAME "0.0.0.0"
ENV PORT 3210

# set default link urls
ENV SITE_URL ""
ENV SHOP_URL ""
ENV ABOUT_URL ""
ENV PRIVACY_URL ""

# set host proxy dns
ENV HTTP_PROXY_URL ""

# General Variables
ENV ACCESS_CODE ""
ENV CUSTOM_MODELS ""
ENV AGENTS_INDEX_URL ""
ENV PLUGINS_INDEX_URL ""

# set default used agent config. this env had some bugs
#ENV DEFAULT_AGENT_CONFIG "model=gpt-4-1106-preview;params.max_tokens=1000;plugins=search-engine,lobe-image-designer"

# API Key selection method
ENV API_KEY_SELECT_MODE "random"

# enabled oauth provider set 1
ENV ENABLE_OAUTH_SSO ""
ENV SSO_PROVIDERS "github"
ENV GITHUB_CLIENT_ID ""
ENV GITHUB_CLIENT_SECRET ""
ENV GOOGLE_CLIENT_ID ""
ENV GOOGLE_CLIENT_SECRET ""
ENV GOOGLE_CLIENT_ID ""
ENV GOOGLE_CLIENT_SECRET ""

# enable Langfuse trace set 1
ENV ENABLE_LANGFUSE ""
ENV LANGFUSE_HOST=""
ENV LANGFUSE_SECRET_KEY ""
ENV LANGFUSE_PUBLIC_KEY ""

# OpenAI
ENV OPENAI_API_KEY ""
ENV OPENAI_PROXY_URL ""

# Azure OpenAI
ENV USE_AZURE_OPENAI ""
ENV AZURE_API_KEY ""
ENV AZURE_API_VERSION ""

# Google
ENV GOOGLE_API_KEY ""
ENV GOOGLE_PROXY_URL ""

# Zhipu
ENV ZHIPU_API_KEY ""

# Moonshot
ENV MOONSHOT_API_KEY ""

# Ollama
ENV OLLAMA_PROXY_URL ""
ENV OLLAMA_CUSTOM_MODELS ""

# Perplexity
ENV PERPLEXITY_API_KEY ""

# Anthropic
ENV ANTHROPIC_API_KEY ""

# Mistral
ENV MISTRAL_API_KEY ""

# OpenRouter
ENV OPENROUTER_API_KEY ""
ENV OPENROUTER_CUSTOM_MODELS ""

# 01.AI
ENV ZEROONE_API_KEY ""

# TogetherAI
ENV TOGETHERAI_API_KEY ""

CMD if [ -n "$HTTP_PROXY_URL" ]; then \
        export HOSTNAME="127.0.0.1"; \
        protocol=$(echo $HTTP_PROXY_URL | cut -d: -f1); \
        host=$(echo $HTTP_PROXY_URL | cut -d/ -f3 | cut -d: -f1); \
        port=$(echo $HTTP_PROXY_URL | cut -d: -f3); \
        conf=/etc/proxychains.conf; \
        echo "strict_chain" > $conf; \
        echo "proxy_dns" >> $conf; \
        echo "remote_dns_subnet 224" >> $conf; \
        echo "tcp_read_time_out 15000" >> $conf; \
        echo "tcp_connect_time_out 8000" >> $conf; \
        echo "localnet 127.0.0.0/255.0.0.0" >> $conf; \
        echo "localnet ::1/128" >> $conf; \
        echo "[ProxyList]" >> $conf; \
        echo "$protocol $host $port" >> $conf; \
        cat /etc/proxychains.conf; \
        proxychains -f $conf node server.js; \
    else \
        node server.js; \
    fi
